import type { NextPage } from 'next'
import dynamic from "next/dynamic";
import Head from 'next/head'
import Image from 'next/image'
import Blockchains from '../components/Blockchains';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className='bg-orange-50'>
      <Head>
        <title>Blockchain Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='p-6 text-4xl font-mono'>Blockchains</h1>
        <Blockchains data={""}></Blockchains>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default dynamic(() => Promise.resolve(Home), { ssr: false });
