import type { NextPage } from 'next'
import dynamic from "next/dynamic";
import Head from 'next/head'
import Image from 'next/image'
import Blockchains from '../components/Blockchains';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Blockchains data={""}></Blockchains>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default dynamic(() => Promise.resolve(Home), { ssr: false });
