import type { NextPage } from 'next'
import dynamic from "next/dynamic";
import Head from 'next/head'
import Image from 'next/image'
import Blockchains from '../components/Blockchains';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className='bg-orange-50'>
      <Head>
        <title>Blockchain Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='p-6 text-4xl font-mono'>Blockchains</h1>
        <Blockchains data={""}></Blockchains>
      </main>

      <footer className="m-4 p-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-orange-200">
        <span className="text-sm text-black-500 sm:text-center dark:text-black-400 font-mono">© 2022 <a href="https://mshrimal.com/" className="hover:underline">Madhur Shrimal</a>. All Rights Reserved.
        </span>
        <ul className="flex flex-wrap items-center mt-3 text-sm text-black-500 dark:text-black-400 sm:mt-0">
            <li>
                <a href="https://github.com/shrimalmadhur/explorers" className="hover:underline text-base font-mono" target='new'>Github</a>
            </li>
        </ul>
      </footer>
    </div>
  )
}

export default dynamic(() => Promise.resolve(Home), { ssr: false });
